### ISSUE TITLE
clang-tidy path should be configurable

### ISSUE THREAD

**Issue by myrgy** [ch1bo/flycheck-clang-tidy#10]
Hi! Thanks a log for great tool!

It would be great to have ability to specify clang-tidy path.

```
  :command ("clang-tidy"
```

**Comment by tastytea** [comment]
You can specify the path in the variable `flycheck-c/c++-clang-tidy-executable`, the variable in the readme(`flycheck-clang-tidy-executable`) is wrong.

**Comment by tastytea** [comment]
I've added the alias `flycheck-clang-tidy-executable` → `flycheck-c/c++-clang-tidy-executable` to keep variable names consistent. So you can use either one of them starting from eb82f734529380217c0cd2a53c0d74102eedc301.

**Comment by myrgy** [comment]
Thanks a lot!
