### ISSUE TITLE
flycheck-clang-tidy-find-default-directory should raise an error, not print a message

### ISSUE THREAD

**Issue by cpitclaudel** [ch1bo/flycheck-clang-tidy#5]
I tried running flycheck-clang-tidy without a config file, and I got the following message:

> if: :working-directory Unable to find config file for c/c++-clang-tidy, you need to create .clang-tidy file in your project root of syntax checker c/c++-clang-tidy does not exist

This is because `flycheck-clang-tidy-find-default-directory` uses `message`, which returns a string, instead of raising an error.

**Comment by tastytea** [comment]
I believe the new method of finding the project root (a9355cc7e2c4f32181e62d8007f6fb84ed509112) fixes this issue.

It first tries to get it from `projectile`, then tries the version control root dir, then looks for `.clang-tidy` and if it still hasn't found it, the current directory is used. If the directory is wrong, you'll get an error from clang-tidy.
