### ISSUE TITLE
Transfer maintainership

### ISSUE THREAD

**Issue by tastytea** [ch1bo/flycheck-clang-tidy#9]
Hi, thanks for your work on this library!

This repository is obviously no longer maintained. Given that this project is already on MELPA, the nicest solution would be if you would transfer maintainership to someone else. I'd be willing to do it if no one else wants.

**Comment by ch1bo** [comment]
Yeah you are right that I am currently not working with C++ and thus not too involved with clang-tidy anymore.

So I would just give you maintainer rights on this repo? Gladly will do and thanks for the PR!

**Comment by tastytea** [comment]
Alright with me. 🙂
